services:
  - type: worker
    name: kent-control-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8705606322:AAEBR17-N_jwKAgbgNDivfPi0SIn0h6rfao
        sync: false
